# Generated by Django 5.1.15 on 2026-01-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinstansi',
            name='aktif',
            field=models.BooleanField(default=False),
        ),
    ]
