# Generated by Django 5.2.10 on 2026-01-14 03:04

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_surat_file_surat'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='mstdatapegawai',
        #     name='id',
        #     field=models.BigAutoField(primary_key=True, serialize=False),
        # ),
        migrations.AddField(
            model_name='mstdatapegawai',
            name='legacy_nip',
            field=models.CharField(blank=True, db_column='legacy_nip', editable=False, max_length=30, null=True, unique=True),
        ),
        # migrations.AddField(
        #     model_name='mstdatapegawai',
        #     name='nama_lengkap_hash',
        #     field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        # ),
        migrations.AddField(
            model_name='mstdatapegawai',
            name='nik_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mstdatapegawai',
            name='nip_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mstdatapegawai',
            name='nama_lengkap',
            field=core.fields.EncryptedTextField(blank=True, db_column='nama_lengkap_enc', null=True),
        ),
        migrations.AlterField(
            model_name='mstdatapegawai',
            name='nik',
            field=core.fields.EncryptedTextField(blank=True, db_column='nik_enc', null=True),
        ),
        migrations.AlterField(
            model_name='mstdatapegawai',
            name='nip',
            field=core.fields.EncryptedTextField(blank=True, db_column='nip_enc', null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='create_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_created_set', to='core.mstdatapegawai', to_field='legacy_nip', verbose_name='Dibuat oleh'),
        ),
        migrations.AlterField(
            model_name='surattahapan',
            name='pejabat',
            field=models.ForeignKey(blank=True, db_column='pejabat_nip', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_tahapan_set', to='core.mstdatapegawai', to_field='legacy_nip'),
        ),
        migrations.AlterField(
            model_name='tajabatan',
            name='nip',
            field=models.ForeignKey(db_column='nip', on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_jabatan_set', to='core.mstdatapegawai', to_field='legacy_nip'),
        ),
    ]
