# Generated by Django 5.2.10 on 2026-01-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_mstdatapegawai_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_created_set', to='core.mstdatapegawai', verbose_name='Dibuat oleh'),
        ),
        migrations.AlterField(
            model_name='surattahapan',
            name='pejabat',
            field=models.ForeignKey(blank=True, db_column='pejabat_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_tahapan_set', to='core.mstdatapegawai'),
        ),
        migrations.AlterField(
            model_name='tajabatan',
            name='nip',
            field=models.ForeignKey(db_column='pegawai_id', on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_jabatan_set', to='core.mstdatapegawai'),
        ),
    ]
