# Generated by Django 5.2.10 on 2026-01-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_surattahapan_instansi_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NipNik',
        ),
    ]
