# Generated by Django 5.2.10 on 2026-01-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_nipnik'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginAttempts',
        ),
    ]
