# Generated by Django 5.2.10 on 2026-01-14 10:48

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_loginattempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logapp',
            name='la_usr',
        ),
        migrations.RemoveField(
            model_name='logbsre',
            name='id_surat',
        ),
        migrations.RemoveField(
            model_name='logbsre',
            name='id_usr',
        ),
        migrations.RemoveField(
            model_name='logbsre',
            name='ins_usr',
        ),
        migrations.RemoveField(
            model_name='logbsre',
            name='jbt_usr',
        ),
        migrations.RemoveField(
            model_name='logbsre',
            name='nik',
        ),
        migrations.RemoveField(
            model_name='logbsre',
            name='nm_usr',
        ),
        migrations.RemoveField(
            model_name='logusr',
            name='id_usr',
        ),
        migrations.RemoveField(
            model_name='logusr',
            name='inputpass',
        ),
        migrations.AddField(
            model_name='logapp',
            name='pegawai',
            field=models.ForeignKey(blank=True, db_column='pegawai_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_app_set', to='core.mstdatapegawai'),
        ),
        migrations.AddField(
            model_name='logapp',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_app_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logbsre',
            name='pegawai',
            field=models.ForeignKey(blank=True, db_column='pegawai_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_bsre_set', to='core.mstdatapegawai'),
        ),
        migrations.AddField(
            model_name='logbsre',
            name='surat',
            field=models.ForeignKey(blank=True, db_column='surat_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_bsre_set', to='core.surat'),
        ),
        migrations.AddField(
            model_name='logusr',
            name='pegawai',
            field=models.ForeignKey(blank=True, db_column='pegawai_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_usr_set', to='core.mstdatapegawai'),
        ),
        migrations.AddField(
            model_name='logusr',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_usr_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logbsre',
            name='ipaddr',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='logusr',
            name='ipaddr',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
