# Generated by Django 5.2.10 on 2026-01-31 06:31

import core.models
import core.upload_paths
import django.core.validators
from django.db import migrations, models


def drop_notifikasi_id_surat_if_exists(apps, schema_editor):
    """
    Aman untuk MySQL: drop kolom id_surat hanya kalau benar-benar ada.
    Juga drop FK constraint kalau ada.
    """
    table = "notifikasi"
    col = "id_surat"

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = %s
              AND COLUMN_NAME = %s
            """,
            [table, col],
        )
        (exists,) = cursor.fetchone()

        if not exists:
            return

        # Drop foreign key constraint kalau kolom id_surat adalah FK
        cursor.execute(
            """
            SELECT CONSTRAINT_NAME
            FROM information_schema.KEY_COLUMN_USAGE
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = %s
              AND COLUMN_NAME = %s
              AND REFERENCED_TABLE_NAME IS NOT NULL
            """,
            [table, col],
        )
        fk_names = [row[0] for row in cursor.fetchall()]

    # Eksekusi DROP FK (pakai schema_editor.execute biar konsisten)
    for fk in fk_names:
        schema_editor.execute(f"ALTER TABLE `{table}` DROP FOREIGN KEY `{fk}`;")

    # Baru drop kolomnya
    schema_editor.execute(f"ALTER TABLE `{table}` DROP COLUMN `{col}`;")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_notifikasi_id_surat_remove_notifikasi_nip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asda',
            options={'managed': False, 'verbose_name': 'ASDA', 'verbose_name_plural': 'ASDA'},
        ),
        migrations.AlterModelOptions(
            name='asdaskpd',
            options={'managed': False, 'verbose_name': 'ASDA-SKPD', 'verbose_name_plural': 'ASDA-SKPD'},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_notifikasi_id_surat_if_exists, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='notifikasi',
                    name='surat',
                ),
            ],
        ),
        migrations.AddField(
            model_name='mstdatapegawai',
            name='specimen_paraf',
            field=models.FileField(blank=True, help_text='File spesimen paraf (PNG disarankan transparan). Disimpan di MinIO.', null=True, upload_to=core.models.specimen_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='mstdatapegawai',
            name='specimen_ttd',
            field=models.FileField(blank=True, help_text='File spesimen tanda tangan (PNG disarankan transparan). Disimpan di MinIO.', null=True, upload_to=core.models.specimen_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='mstdatapegawai',
            name='specimen_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='qr_logo',
            field=models.FileField(blank=True, help_text='Logo PNG untuk ditaruh di tengah QR (disimpan di MinIO).', null=True, upload_to=core.models.setting_upload_to, validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
        migrations.AddField(
            model_name='setting',
            name='qr_marker_text',
            field=models.CharField(blank=True, default='[QR]', help_text='Marker teks untuk posisi QR di template PDF.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='ttd_marker_text',
            field=models.CharField(blank=True, default='[TTD]', help_text='Marker teks untuk posisi spesimen/paraf di template PDF.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='surat',
            name='file_signed',
            field=models.FileField(blank=True, help_text='PDF final setelah TTE cryptographic.', null=True, upload_to=core.upload_paths.surat_pdf_upload_to),
        ),
        migrations.AddField(
            model_name='surat',
            name='file_surat_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='surat',
            name='file_unsigned',
            field=models.FileField(blank=True, help_text='PDF hasil stamping (QR/logo/(optional) spesimen), belum TTE cryptographic.', null=True, upload_to=core.upload_paths.surat_pdf_upload_to),
        ),
        migrations.AddField(
            model_name='surat',
            name='file_unsigned_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='surat',
            name='stamp_last_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surat',
            name='stamp_version',
            field=models.IntegerField(default=1),
        ),
    ]
