# Generated by Django 5.2.10 on 2026-01-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_asda_options_alter_asdaskpd_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='qr_fallback_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setting',
            name='qr_fallback_x',
            field=models.IntegerField(default=450),
        ),
        migrations.AddField(
            model_name='setting',
            name='qr_fallback_y',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='setting',
            name='qr_height',
            field=models.IntegerField(default=110),
        ),
        migrations.AddField(
            model_name='setting',
            name='qr_width',
            field=models.IntegerField(default=110),
        ),
        migrations.AddField(
            model_name='setting',
            name='stamp_mode',
            field=models.CharField(choices=[('marker', 'Marker'), ('all_markers', 'All Markers')], default='marker', max_length=16),
        ),
        migrations.AddField(
            model_name='setting',
            name='ttd_fallback_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setting',
            name='ttd_fallback_x',
            field=models.IntegerField(default=320),
        ),
        migrations.AddField(
            model_name='setting',
            name='ttd_fallback_y',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='setting',
            name='ttd_height',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='setting',
            name='ttd_width',
            field=models.IntegerField(default=120),
        ),
    ]
