# Generated by Django 5.2.10 on 2026-01-31 07:42

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_setting_qr_fallback_page_setting_qr_fallback_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='bsre_logo',
            field=models.FileField(blank=True, help_text='Logo PNG BSrE untuk footnote (disimpan di MinIO).', null=True, upload_to=core.models.setting_upload_to, validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
        migrations.AddField(
            model_name='setting',
            name='footnote_box_width',
            field=models.IntegerField(default=480),
        ),
        migrations.AddField(
            model_name='setting',
            name='footnote_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='footnote_fallback_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setting',
            name='footnote_fallback_x',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='setting',
            name='footnote_fallback_y',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='setting',
            name='footnote_font_size',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='setting',
            name='footnote_line_gap',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='setting',
            name='footnote_logo_h',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='setting',
            name='footnote_logo_w',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='setting',
            name='footnote_marker_text',
            field=models.CharField(blank=True, default='[FOOTNOTE]', help_text='Marker teks untuk posisi footnote di template PDF.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='footnote_text',
            field=models.TextField(blank=True, default='Dokumen ini telah ditandatangani secara elektronik menggunakan sertifikat elektronik yang\nditerbitkan oleh Balai Besar Sertifikasi Elektronik (BSrE) Badan Siber dan Sandi Negara', null=True),
        ),
    ]
