# Generated by Django 5.2.10 on 2026-01-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_setting_bsre_logo_setting_footnote_box_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='verify_base_url',
            field=models.CharField(blank=True, help_text='Base URL untuk verifikasi QR TTE (contoh: https://tte.bekasikab.go.id/verifikasi)', max_length=255, null=True),
        ),
    ]
