# Generated by Django 5.2.10 on 2026-02-02 06:12

import core.models
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_setting_verify_base_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratTemplate',
            fields=[
                ('id_template', models.AutoField(primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_marker_text', models.CharField(blank=True, max_length=32, null=True)),
                ('ttd_marker_text', models.CharField(blank=True, max_length=32, null=True)),
                ('stamp_mode', models.CharField(blank=True, choices=[('marker', 'Marker'), ('all_markers', 'All Markers')], max_length=16, null=True)),
                ('qr_width', models.IntegerField(blank=True, null=True)),
                ('qr_height', models.IntegerField(blank=True, null=True)),
                ('ttd_width', models.IntegerField(blank=True, null=True)),
                ('ttd_height', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Template Surat',
                'verbose_name_plural': 'Template Surat',
                'db_table': 'surat_template',
            },
        ),
        migrations.AddField(
            model_name='mstjabatan',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mstjabatan',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mstjabatan',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mstjabatan',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refinstansi',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.refinstansi'),
        ),
        migrations.AddField(
            model_name='refinstansi',
            name='tipe',
            field=models.CharField(choices=[('SKPD', 'SKPD'), ('UNIT', 'UNIT')], default='SKPD', max_length=10),
        ),
        migrations.AddField(
            model_name='surattahapan',
            name='file_signed',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_to_tahapan_signed, verbose_name='File signed (per tahapan)'),
        ),
        migrations.AddField(
            model_name='surattahapan',
            name='signed_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='surattahapan',
            name='signed_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='surattahapan',
            name='signed_version_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mstjabatan',
            name='jenis_jabatan',
            field=models.CharField(blank=True, choices=[('S', 'Struktural'), ('F', 'Fungsional')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mstjabatan',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, db_column='id_parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.mstjabatan', verbose_name='Parent Jabatan'),
        ),
        migrations.AddIndex(
            model_name='mstjabatan',
            index=models.Index(fields=['tree_id', 'lft'], name='core_mstjabatan_tree_id_lf1e8a'),
        ),
        migrations.AddField(
            model_name='surat',
            name='template_ref',
            field=models.ForeignKey(blank=True, db_column='template_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_set', to='core.surattemplate', verbose_name='Template Surat'),
        ),
    ]
