# Generated by Django 5.2.10 on 2026-02-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_surattemplate_mstjabatan_level_mstjabatan_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surattemplate',
            name='qr_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surattemplate',
            name='qr_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
