# Generated by Django 5.2.10 on 2026-03-14 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_surattemplate_specimen_bg_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surattemplate',
            name='specimen_marker_text',
        ),
        migrations.RemoveField(
            model_name='surattemplate',
            name='specimen_offset_x',
        ),
        migrations.RemoveField(
            model_name='surattemplate',
            name='specimen_offset_y',
        ),
        migrations.RemoveField(
            model_name='surattemplate',
            name='specimen_pointer_mode',
        ),
        migrations.RemoveField(
            model_name='surattemplate',
            name='specimen_pointer_text',
        ),
        migrations.AlterField(
            model_name='surattemplate',
            name='specimen_mode',
            field=models.CharField(blank=True, choices=[('upload', 'Upload'), ('generated', 'Generated')], max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='SuratTemplateSpecimenSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan_signer', models.PositiveIntegerField(help_text='Urutan penandatangan/specimen. 1 = signer pertama, 2 = signer kedua, dst.')),
                ('nama_slot', models.CharField(blank=True, help_text='Nama bebas untuk memudahkan admin. Contoh: Penandatangan Utama / Mengetahui', max_length=100, null=True)),
                ('placement_type', models.CharField(choices=[('marker', 'Marker'), ('pointer', 'Pointer Text'), ('fallback', 'Fallback Koordinat')], default='marker', max_length=16)),
                ('marker_text', models.CharField(blank=True, help_text='Contoh: [SPESIMEN1], [SPESIMEN2]', max_length=64, null=True)),
                ('pointer_text', models.CharField(blank=True, help_text='Contoh: "Hormat kami," atau "Mengetahui."', max_length=128, null=True)),
                ('pointer_mode', models.CharField(choices=[('below', 'Below'), ('above', 'Above'), ('left', 'Left'), ('right', 'Right')], default='below', max_length=16)),
                ('offset_x', models.IntegerField(default=0)),
                ('offset_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('fallback_page', models.IntegerField(blank=True, help_text='0 atau kosong = halaman terakhir', null=True)),
                ('fallback_x', models.IntegerField(blank=True, null=True)),
                ('fallback_y', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(db_column='template_id', on_delete=django.db.models.deletion.CASCADE, related_name='specimen_slots', to='core.surattemplate')),
            ],
            options={
                'db_table': 'surat_template_specimen_slot',
                'ordering': ['template_id', 'urutan_signer'],
                'unique_together': {('template', 'urutan_signer')},
            },
        ),
    ]
