# Generated by Django 5.2.10 on 2026-01-14 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_pegawai_ref_id'),
        ('core', '0006_mstdatapegawai_id_mstdatapegawai_nama_lengkap_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legacy_pegawai_nip',
            field=models.CharField(blank=True, db_column='pegawai_id', editable=False, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pegawai',
            field=models.ForeignKey(blank=True, db_column='pegawai_ref_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.mstdatapegawai'),
        ),
    ]
