# Generated by Django 5.2.10 on 2026-01-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_legacy_pegawai_nip_alter_user_pegawai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='legacy_pegawai_nip',
        ),
        migrations.AddField(
            model_name='user',
            name='username_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
