# Generated by Django 5.2.10 on 2026-02-02 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_legacy_pegawai_nip_user_username_hash'),
        ('core', '0022_surattemplate_mstjabatan_level_mstjabatan_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instansi',
            field=models.ForeignKey(blank=True, db_column='instansi_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_users', to='core.refinstansi'),
        ),
    ]
