server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html/tte/dist;

	index index.html index.htm index.nginx-debian.html;

	add_header Content-Security-Policy "default-src 'self' * data: blob:; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https: blob:; font-src 'self' data: https:;" always;

	server_name tte.gabuspucung.id;
	client_max_body_size 10M;

	location /tte-static/ {
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_pass http://10.69.69.14:9000/tte-static/;
	}

	location /tte-media/ {
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_pass http://10.69.69.14:9000/tte-media/;
	}

	location ~ ^/(admin|api|Lihat|verifikasi)/ {
		include proxy_params;
		proxy_pass http://unix:/run/tte.sock;
	}

	location / {
		try_files $uri $uri/ /index.html;
	}

}
