# Generated by Django 5.1.15 on 2026-01-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_refinstansi_aktif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surat',
            name='instansi',
        ),
        migrations.AlterField(
            model_name='surat',
            name='file_surat',
            field=models.FileField(blank=True, help_text='File surat di MinIO (bukan file upload Django).', null=True, upload_to=''),
        ),
    ]
