# Generated by Django 5.2.10 on 2026-01-14 02:39

import core.upload_paths
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_surat_instansi_alter_surat_file_surat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='file_surat',
            field=models.FileField(blank=True, help_text='Upload PDF. Disimpan ke MinIO: surat/YYYY/MM/DD/ (private, pakai presigned URL).', null=True, upload_to=core.upload_paths.surat_pdf_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), core.validators.validate_pdf_magic, core.validators.validate_max_10mb]),
        ),
    ]
