# Generated by Django 5.2.10 on 2026-01-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mstdatapegawai_id_mstdatapegawai_legacy_nip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstdatapegawai',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='mstdatapegawai',
            name='nama_lengkap_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
