# Generated by Django 5.2.10 on 2026-01-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_null_plain_nik_nama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstdatapegawai',
            name='status',
        ),
        migrations.AddField(
            model_name='mstdatapegawai',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
