# Generated by Django 5.2.10 on 2026-01-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_surat_created_by_alter_surattahapan_pejabat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstdatapegawai',
            name='legacy_nip',
        ),
    ]
