# Generated by Django 5.2.10 on 2026-01-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_mstdatapegawai_legacy_nip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surattahapan',
            name='instansi',
        ),
        migrations.RemoveField(
            model_name='surattahapan',
            name='pejabat_nama',
        ),
    ]
