# Generated by Django 5.2.10 on 2026-01-14 10:57

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_logapp_la_usr_remove_logbsre_id_surat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbsre',
            name='ipaddr',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
