# Generated by Django 5.2.10 on 2026-01-14 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_logbsre_ipaddr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifikasi',
            name='id_surat',
        ),
        migrations.RemoveField(
            model_name='notifikasi',
            name='nip',
        ),
        migrations.AlterUniqueTogether(
            name='telegramnotif',
            unique_together={('pegawai', 'tn_chat_id')},
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='pegawai',
            field=models.ForeignKey(blank=True, db_column='pegawai_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifikasi_set', to='core.mstdatapegawai'),
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='surat',
            field=models.ForeignKey(blank=True, db_column='id_surat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifikasi_set', to='core.surat'),
        ),
        migrations.AddField(
            model_name='telegramnotif',
            name='pegawai',
            field=models.ForeignKey(blank=True, db_column='pegawai_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_notif_set', to='core.mstdatapegawai'),
        ),
        migrations.AlterField(
            model_name='notifikasi',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='notifikasi',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Paraf'), ('2', 'TTD'), ('3', 'Pembuat Surat'), ('4', 'Surat Selesai')], db_index=True, max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='telegramnotif',
            name='tn_nip',
        ),
    ]
