# Generated by Django 5.2.10 on 2026-03-01 13:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_surattemplate_qr_x_surattemplate_qr_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='logusr',
            name='aktivitas',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='is_finish',
            field=models.IntegerField(blank=True, choices=[(1, 'On Process'), (2, 'Pending'), (3, 'Finish')], default=1, null=True),
        ),
        migrations.CreateModel(
            name='SuratVerifikasi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_access_at', models.DateTimeField(blank=True, null=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('surat', models.ForeignKey(db_column='id_surat', on_delete=django.db.models.deletion.CASCADE, related_name='verifikasi_set', to='core.surat')),
            ],
            options={
                'verbose_name': 'Surat Verifikasi',
                'verbose_name_plural': 'Surat Verifikasi',
                'db_table': 'surat_verifikasi',
            },
        ),
    ]
