# Generated by Django 5.2.10 on 2026-03-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_logusr_aktivitas_alter_surat_is_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surattemplate',
            name='specimen_bg_color',
            field=models.CharField(blank=True, default='#d9d9d9', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='surattemplate',
            name='specimen_border_color',
            field=models.CharField(blank=True, default='#000000', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='surattemplate',
            name='specimen_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surattemplate',
            name='specimen_marker_text',
            field=models.CharField(blank=True, help_text='Contoh: [SPESIMEN{n}] atau [SPESIMEN]', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='surattemplate',
            name='specimen_mode',
            field=models.CharField(blank=True, choices=[('upload', 'Upload'), ('generated', 'Generated')], help_text='upload=pakai file specimen pegawai, generated=dibuat otomatis oleh sistem', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='surattemplate',
            name='specimen_offset_x',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='surattemplate',
            name='specimen_offset_y',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='surattemplate',
            name='specimen_pointer_mode',
            field=models.CharField(blank=True, choices=[('below', 'Below'), ('above', 'Above'), ('left', 'Left'), ('right', 'Right')], default='below', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='surattemplate',
            name='specimen_pointer_text',
            field=models.CharField(blank=True, help_text='Contoh: Hormat kami,', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='surattemplate',
            name='specimen_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
